{
	"data":
	{
		"easy": {
			'cars': [
				{src:"🚗", visible: true, paired: false, clickable: false},
				{src:"🚕", visible: true, paired: false, clickable: false},
				{src:"🚙", visible: true, paired: false, clickable: false},
				{src:"🚌", visible: true, paired: false, clickable: false},
				{src:"🚎", visible: true, paired: false, clickable: false},
				{src:"🚓", visible: true, paired: false, clickable: false},
				{src:"🚑", visible: true, paired: false, clickable: false},
				{src:"🚒", visible: true, paired: false, clickable: false},
				{src:"🚚", visible: true, paired: false, clickable: false},
				{src:"🚜", visible: true, paired: false, clickable: false},
				{src:"🚛", visible: true, paired: false, clickable: false},
				{src:"🏎", visible: true, paired: false, clickable: false},
				{src:"🚲", visible: true, paired: false, clickable: false},
			],
			'animals': [
				{src:"🐶", visible: true, paired: false, clickable: false},
				{src:"🐭", visible: true, paired: false, clickable: false},
				{src:"🐱", visible: true, paired: false, clickable: false},
				{src:"🐹", visible: true, paired: false, clickable: false},
				{src:"🐰", visible: true, paired: false, clickable: false},
				{src:"🐼", visible: true, paired: false, clickable: false},
				{src:"🐨", visible: true, paired: false, clickable: false},
				{src:"🐯", visible: true, paired: false, clickable: false},
				{src:"🦁", visible: true, paired: false, clickable: false},
				{src:"🐮", visible: true, paired: false, clickable: false},
				{src:"🐷", visible: true, paired: false, clickable: false},
				{src:"🐵", visible: true, paired: false, clickable: false},
				{src:"🐸", visible: true, paired: false, clickable: false},
			],
			'fruits': [
				{src:"🌽", visible: true, paired: false, clickable: false},
				{src:"🌶", visible: true, paired: false, clickable: false},
				{src:"🍑", visible: true, paired: false, clickable: false},
				{src:"🍒", visible: true, paired: false, clickable: false},
				{src:"🍈", visible: true, paired: false, clickable: false},
				{src:"🍓", visible: true, paired: false, clickable: false},
				{src:"🍇", visible: true, paired: false, clickable: false},
				{src:"🍉", visible: true, paired: false, clickable: false},
				{src:"🍌", visible: true, paired: false, clickable: false},
				{src:"🍋", visible: true, paired: false, clickable: false},
				{src:"🍎", visible: true, paired: false, clickable: false},
				{src:"🍺", visible: true, paired: false, clickable: false},
				{src:"🍲", visible: true, paired: false, clickable: false},
				{src:"🍷", visible: true, paired: false, clickable: false},
				{src:"🍸", visible: true, paired: false, clickable: false},
				{src:"🍹", visible: true, paired: false, clickable: false},
				{src:"🍜", visible: true, paired: false, clickable: false},
				{src:"🍶", visible: true, paired: false, clickable: false},
				{src:"🍵", visible: true, paired: false, clickable: false},
				{src:"🍝", visible: true, paired: false, clickable: false},
			]
		},
		"medium": {
			'buildings': [
				{src:"🏤", visible: true, paired: false, clickable: false},
				{src:"🏥", visible: true, paired: false, clickable: false},
				{src:"🏦", visible: true, paired: false, clickable: false},
				{src:"🏨", visible: true, paired: false, clickable: false},
				{src:"🏪", visible: true, paired: false, clickable: false},
				{src:"🏫", visible: true, paired: false, clickable: false},
				{src:"🏩", visible: true, paired: false, clickable: false},
				{src:"💒", visible: true, paired: false, clickable: false},
				{src:"🏛", visible: true, paired: false, clickable: false},
				{src:"⛪", visible: true, paired: false, clickable: false},
				{src:"🕌", visible: true, paired: false, clickable: false},
				{src:"🕍", visible: true, paired: false, clickable: false},
			],
			'food': [
				{src:"🍔", visible: true, paired: false, clickable: false},
				{src:"🍟", visible: true, paired: false, clickable: false},
				{src:"🌮", visible: true, paired: false, clickable: false},
				{src:"🌯", visible: true, paired: false, clickable: false},
				{src:"🍕", visible: true, paired: false, clickable: false},
				{src:"🍖", visible: true, paired: false, clickable: false},
				{src:"🍗", visible: true, paired: false, clickable: false},
				{src:"🍠", visible: true, paired: false, clickable: false},
				{src:"🍞", visible: true, paired: false, clickable: false},
				{src:"🍯", visible: true, paired: false, clickable: false},
				{src:"🍩", visible: true, paired: false, clickable: false},
				{src:"🍪", visible: true, paired: false, clickable: false},
				{src:"🧀", visible: true, paired: false, clickable: false},
				{src:"🌰", visible: true, paired: false, clickable: false},
				{src:"🍫", visible: true, paired: false, clickable: false},
			],
			'plants': [
				{src:"🌲", visible: true, paired: false, clickable: false},
				{src:"🌳", visible: true, paired: false, clickable: false},
				{src:"🌴", visible: true, paired: false, clickable: false},
				{src:"🌱", visible: true, paired: false, clickable: false},
				{src:"🌿", visible: true, paired: false, clickable: false},
				{src:"🍀", visible: true, paired: false, clickable: false},
				{src:"🍃", visible: true, paired: false, clickable: false},
				{src:"🍂", visible: true, paired: false, clickable: false},
				{src:"🍁", visible: true, paired: false, clickable: false},
				{src:"🍄", visible: true, paired: false, clickable: false},
				{src:"🌾", visible: true, paired: false, clickable: false},
				{src:"💐", visible: true, paired: false, clickable: false},
				{src:"🌷", visible: true, paired: false, clickable: false},
				{src:"🌹", visible: true, paired: false, clickable: false},
				{src:"🌼", visible: true, paired: false, clickable: false},
				{src:"🌵", visible: true, paired: false, clickable: false},
				{src:"🌺", visible: true, paired: false, clickable: false},
				{src:"🌸", visible: true, paired: false, clickable: false},
			]
		},
		"hard": {
			'flags': [
				{src:"🇦🇩", visible: true, paired: false, clickable: false},
				{src:"🇩🇿", visible: true, paired: false, clickable: false},
				{src:"🇪🇸", visible: true, paired: false, clickable: false},
				{src:"🇺🇦", visible: true, paired: false, clickable: false},
				{src:"🇦🇪", visible: true, paired: false, clickable: false},
				{src:"🇵🇪", visible: true, paired: false, clickable: false},
				{src:"🇪🇨", visible: true, paired: false, clickable: false},
				{src:"🇻🇳", visible: true, paired: false, clickable: false},
				{src:"🇵🇹", visible: true, paired: false, clickable: false},
				{src:"🇵🇱", visible: true, paired: false, clickable: false},
				{src:"🇺🇾", visible: true, paired: false, clickable: false},
				{src:"🇬🇧", visible: true, paired: false, clickable: false},
				{src:"🇲🇾", visible: true, paired: false, clickable: false},
				{src:"🇮🇷", visible: true, paired: false, clickable: false},
				{src:"🇹🇩", visible: true, paired: false, clickable: false},
				{src:"🇰🇿", visible: true, paired: false, clickable: false},
				{src:"🇧🇩", visible: true, paired: false, clickable: false},
				{src:"🇸🇿", visible: true, paired: false, clickable: false},
				{src:"🇾🇪", visible: true, paired: false, clickable: false},
			],
			'moon': [
				{src:"🌝", visible: true, paired: false, clickable: false},
				{src:"🌚", visible: true, paired: false, clickable: false},
				{src:"🌔", visible: true, paired: false, clickable: false},
				{src:"🌓", visible: true, paired: false, clickable: false},
				{src:"🌒", visible: true, paired: false, clickable: false},
				{src:"🌑", visible: true, paired: false, clickable: false},
				{src:"🌘", visible: true, paired: false, clickable: false},
				{src:"🌗", visible: true, paired: false, clickable: false},
				{src:"🌖", visible: true, paired: false, clickable: false},
				{src:"🌕", visible: true, paired: false, clickable: false},
				{src:"🌞", visible: true, paired: false, clickable: false},
				{src:"🌛", visible: true, paired: false, clickable: false},
				{src:"⭐", visible: true, paired: false, clickable: false},
				{src:"💫", visible: true, paired: false, clickable: false},
			],
			'faces': [
				{src:"😪", visible: true, paired: false, clickable: false},
				{src:"😓", visible: true, paired: false, clickable: false},
				{src:"😴", visible: true, paired: false, clickable: false},
				{src:"😤", visible: true, paired: false, clickable: false},
				{src:"😳", visible: true, paired: false, clickable: false},
				{src:"😄", visible: true, paired: false, clickable: false},
				{src:"😁", visible: true, paired: false, clickable: false},
				{src:"😆", visible: true, paired: false, clickable: false},
				{src:"😂", visible: true, paired: false, clickable: false},
				{src:"😛", visible: true, paired: false, clickable: false},
				{src:"🤗", visible: true, paired: false, clickable: false},
				{src:"😵", visible: true, paired: false, clickable: false},
				{src:"🤕", visible: true, paired: false, clickable: false},
				{src:"😛", visible: true, paired: false, clickable: false},
				{src:"🤒", visible: true, paired: false, clickable: false},
				{src:"😭", visible: true, paired: false, clickable: false},
				{src:"🤐", visible: true, paired: false, clickable: false},
				{src:"😇", visible: true, paired: false, clickable: false},
				{src:"🤓", visible: true, paired: false, clickable: false},
				{src:"😘", visible: true, paired: false, clickable: false},
				{src:"😗", visible: true, paired: false, clickable: false},
				{src:"🤔", visible: true, paired: false, clickable: false},
			]
		}
	}
}
